// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10jC4dbvIKnAeIfGuIJhAC8pK3akCZCk',
    appId: '1:172626856664:web:d45ff631cda41b995fa5ad',
    messagingSenderId: '172626856664',
    projectId: 'bookify-fa0ca',
    authDomain: 'bookify-fa0ca.firebaseapp.com',
    storageBucket: 'bookify-fa0ca.firebasestorage.app',
    measurementId: 'G-1VT2TSBSS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvbLnSmR5gyoA6iAXRzUTyRjXtiJUb8Y',
    appId: '1:172626856664:android:76c1ad08f01948595fa5ad',
    messagingSenderId: '172626856664',
    projectId: 'bookify-fa0ca',
    storageBucket: 'bookify-fa0ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJRrtjUtcuxd_xX-5BDnLLvfgSpIDOuHg',
    appId: '1:172626856664:ios:3e0e12f7ad08e0d75fa5ad',
    messagingSenderId: '172626856664',
    projectId: 'bookify-fa0ca',
    storageBucket: 'bookify-fa0ca.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJRrtjUtcuxd_xX-5BDnLLvfgSpIDOuHg',
    appId: '1:172626856664:ios:3e0e12f7ad08e0d75fa5ad',
    messagingSenderId: '172626856664',
    projectId: 'bookify-fa0ca',
    storageBucket: 'bookify-fa0ca.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB10jC4dbvIKnAeIfGuIJhAC8pK3akCZCk',
    appId: '1:172626856664:web:98ce95f4a31712e45fa5ad',
    messagingSenderId: '172626856664',
    projectId: 'bookify-fa0ca',
    authDomain: 'bookify-fa0ca.firebaseapp.com',
    storageBucket: 'bookify-fa0ca.firebasestorage.app',
    measurementId: 'G-QX51B68Q5C',
  );
}
